### ISSUE TITLE
Running allplots.py

### ISSUE THREAD

**Issue by mrmrwinter** [Gabaldonlab/karyon#2]
Hi, I really like the nQuire plots included in this, and think those among the others could be really useful. I have the required files for the allplots.py script - vcf, pileup, etc - but cant get it working.

I am getting the following error message:

```
Traceback (most recent call last):
  File "bin/allplots.py", line 100, in <module>
    config_dict["KAT"][0], 
KeyError: 'KAT'
```

I am running the following command:

```
python3 allplots.py \
-f redundans _reduced.fasta \
-v file.vcf -p file.mpileup \
-b file.bam \
-l library_to_make_fasta.fastq \
-o out_file
```

I have installed with both lightinstall.sh and install.sh and am getting the same message.

Can you help? I will try the docker image int he meantime, many thanks.

**Comment by MANaranjo** [comment]
Hello and thanks for your interest in the program.

It seems the problem comes from parsing the configuration file, as it seems
unable to find KAT in it. Can you send me the configuration.txt file inside
the bin directory?

Best,

Miguel Naranjo-Ortiz

**Comment by mrmrwinter** [comment]
Hi Miguel,

KAT is indeed not in it. 

```
+karyon
@/home/karyon/
+redundans
@/home/karyon/scripts/dependencies/redundans/
+BWA

@/home/karyon/scripts/dependencies/bwa-0.7.15/
+GATK
@/home/karyon/scripts/dependencies/gatk-4.1.9.0/gatk
+samtools
@/home/karyon/scripts/dependencies/samtools-1.9/
+bcftools
@/home/karyon/scripts/dependencies/bcftools-1.9/
+picard-tools
@/home/karyon/scripts/dependencies/picard-tools-1.78/
+SPAdes
@/home/karyon/scripts/dependencies/SPAdes-3.9.0-Linux/
+KAT
@
+nQuire
@/home/karyon/scripts/dependencies/nQuire/nQuire
+SOAPdeNovo
@/home/karyon/scripts/dependencies/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer
+trimmomatic
@/home/karyon/scripts/dependencies/Trimmomatic-0.36/
```

I have installed KAT manually using brew, and the error is no longer popping up. 

Now im getting errors for missing dependencies: pyutil, pysam, seaborn

I installed these through conda, now i am getting the following:
```
Traceback (most recent call last):
  File "bin/allplots.py", line 93, in <module>
    allplots(window_size, 
  File "/home/mike/software/karyon/bin/karyonplots.py", line 504, in allplots
    var_v_cov(vcf, mpileup, window_size, newpath, lendict, scafminsize, scafmaxsize)
  File "/home/mike/software/karyon/bin/karyonplots.py", line 112, in var_v_cov
    mean_cov = extract_pileup_data(pileup_file, window_size, lendict, scafminsize, scafmaxsize)
  File "/home/mike/software/karyon/bin/karyonplots.py", line 84, in extract_pileup_data
    for line in pileup_file:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Best
